name: rfs-app
services:
  php:
    build:
      dockerfile: .docker/php/docker-extensions
    volumes:
      - .:/var/www/html
  web:
    image: nginx:alpine
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - .docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html:ro
  database:
    image: mysql:8
    ports:
        -  "33061:3306"
    volumes:
      - .docker/database/init:/docker-entrypoint-initdb.d
    command:
      - --mysql-native-password=ON
      - --log-error-verbosity=3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # Use the `DB_DATABASE` from the .env file if it set
      MYSQL_DATABASE: ${DB_DATABASE}
